'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const {JSDOM}=require('jsdom'); const {createHarness}=require('./fixtures/tag-library.cjs'); const fs=require('node:fs'); const path=require('node:path');
async function setup(t) { assert.ok(fs.existsSync(path.join(__dirname,'../src/views/tag-location-view.js')),'location picker exists'); const {createTagLocationView}=require('../src/views/tag-location-view'); const h=createHarness(); await h.ready; const dom=new JSDOM('<body><button id="origin">Origin</button></body>'); const document=dom.window.document; document.querySelector('#origin').focus(); const view=createTagLocationView({document,catalog:h.library,getLocale:()=> 'en-US'}); t.after(()=>{view.dispose();dom.window.close();}); const set=(key,value)=>{const node=document.querySelector(`[data-location-${key}]`); node.value=value; node.dispatchEvent(new dom.window.Event('change',{bubbles:true}));}; return {...h,dom,document,view,set}; }
test('new parent and child stay local through confirm and cancel',async t=>{ const h=await setup(t); const pending=h.view.choose({kind:'favorite'}); h.set('parent','__create__'); h.set('parent-name','New page'); h.set('child','__create__'); h.set('child-name','New group'); h.document.querySelector('[data-location-confirm]').click(); assert.deepEqual(await pending,{kind:'favorite',page:{create:{name:'New page'}},group:{create:{name:'New group'}}}); assert.equal(h.repository.saveCount,0); const cancel=h.view.choose({kind:'taxonomy'}); h.document.querySelector('[data-location-cancel]').click(); assert.equal(await cancel,null); assert.equal(h.repository.saveCount,0); assert.equal(h.document.activeElement.id,'origin'); });
test('parent changes clear child and duplicate sibling name identifies existing item',async t=>{ const h=await setup(t); const pending=h.view.choose({kind:'taxonomy',current:{kind:'taxonomy',category:{id:'hair'},subcategory:{id:'color'}}}); h.set('child','__create__'); h.set('child-name','  颜色  '); h.document.querySelector('[data-location-confirm]').click(); assert.match(h.document.querySelector('[data-location-error]').textContent,/颜色/); assert.equal(h.document.querySelector('[data-tag-location-overlay]').hidden,false); h.set('parent','__create__'); assert.equal(h.document.querySelector('[data-location-child]').value,''); h.document.querySelector('[data-location-cancel]').click(); assert.equal(await pending,null); });
test('browser scripts register dual factories and CSS explicitly hides overlays',()=>{ const vm=require('node:vm'); const context=vm.createContext({}); for(const file of ['tag-location-view','tag-editor-view']) { const p=path.join(__dirname,`../src/views/${file}.js`); assert.ok(fs.existsSync(p),'component exists'); vm.runInContext(fs.readFileSync(p,'utf8'),context); } assert.equal(typeof context.AppViews.tagLocation.createTagLocationView,'function'); assert.equal(typeof context.AppViews.tagEditor.createTagEditorView,'function'); assert.match(fs.readFileSync(path.join(__dirname,'../src/tag-editor.css'),'utf8'),/\.tag-editor-overlay\[hidden\]/); });
test('modal computed layers follow active stack across creation order and restack after close',()=>{
 const {createDialogTools}=require('../src/views/tag-location-view');const dom=new JSDOM('<body></body>');const document=dom.window.document;const style=document.createElement('style');style.textContent=fs.readFileSync(path.join(__dirname,'../src/tag-editor.css'),'utf8');document.head.append(style);
 const child=createDialogTools(document,'location'),parent=createDialogTools(document,'editor'),discard=createDialogTools(document,'discard');const z=dialog=>Number(dom.window.getComputedStyle(dialog.overlay).zIndex);
 parent.open();assert.equal(z(parent),1000);child.open();assert.ok(z(child)>z(parent));discard.open();assert.ok(z(discard)>z(child));child.close();assert.equal(z(discard),1001);assert.equal(child.overlay.style.zIndex,'');discard.close();child.open();assert.equal(z(child),1001);parent.close();assert.equal(z(child),1000);child.close();parent.open();discard.open();assert.ok(z(discard)>z(parent));
 discard.dispose();parent.dispose();child.dispose();dom.window.close();
});
