'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { createHarness, makeBase, emptyUserDocument } = require('./fixtures/tag-library.cjs');
const placement = { kind: 'favorite', page: { id: 'home' }, group: { id: 'daily' } };
let operation = 0;
const run = (library, command, options = {}) => library.execute(command, { operationId: `test-${++operation}`, ...options });
test('favorite membership shares one mutable identity and publishes after durable save', async () => {
  const h = createHarness(); await h.ready;
  const events = []; h.library.subscribe(e => events.push(e));
  const count = h.library.listTags({ scope: 'all', includeAdult: true }).total;
  const added = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  assert.equal(added.ok, true);
  assert.equal(h.library.listTags({ scope: 'all', includeAdult: true }).total, count);
  const duplicate = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  assert.equal(duplicate.data.changed, false);
  assert.equal(h.repository.saveCount, 1);
  const delay = h.controls.delayNextSave();
  const pending = run(h.library, { type: 'saveTag', tagId: 'blue_hair', patch: { content: 'azure hair', note: '共享备注' } });
  await delay.started;
  assert.equal(h.library.getTag('blue_hair').content, 'blue hair'); assert.equal(events.length, 1);
  delay.release(); assert.equal((await pending).ok, true);
  const row = h.library.listTags({ scope: 'favorites', includeAdult: true }).items[0];
  assert.equal(row.content, 'azure hair'); assert.equal(row.note, '共享备注');
  assert.equal(h.library.getMemberships('blue_hair').length, 1);
  assert.deepEqual(events[1].changedCharacterIds.sort(), ['alice', 'bob']);
  assert.deepEqual(events[1].changedMembershipIds, [added.data.membershipId]);
  assert.equal((await h.reload()).getTag('blue_hair').content, 'azure hair');
});
test('write failures and concurrent revisions do not publish drafts; operation ids deduplicate canonical commands', async () => {
  const h = createHarness(); await h.ready; const events = []; h.library.subscribe(e => events.push(e));
  const command = { type: 'saveTag', tagId: 'blue_hair', patch: { note: 'first', aliases: ['azure'] } };
  h.controls.failNextSave();
  assert.equal((await run(h.library, command, { operationId: 'retry' })).error.code, 'STORAGE_WRITE_FAILED');
  assert.equal(h.library.revision(), 0); assert.equal(events.length, 0);
  assert.equal((await run(h.library, command, { operationId: 'retry' })).ok, true);
  const count = h.repository.saveCount;
  assert.equal((await run(h.library, { patch: { aliases: ['azure'], note: 'first' }, tagId: 'blue_hair', type: 'saveTag' }, { operationId: 'retry' })).ok, true);
  assert.equal(h.repository.saveCount, count);
  assert.equal((await run(h.library, { ...command, patch: { note: 'second' } }, { operationId: 'retry' })).error.code, 'OPERATION_CONFLICT');
  const delay = h.controls.delayNextSave(); const revision = h.library.revision();
  const first = run(h.library, { ...command, patch: { note: 'second' } }, { expectedRevision: revision }); await delay.started;
  const second = run(h.library, { ...command, patch: { note: 'third' } }, { expectedRevision: revision });
  delay.release(); assert.equal((await first).ok, true); assert.equal((await second).error.code, 'REVISION_CONFLICT');
  assert.equal(h.library.getTag('blue_hair').note, 'second');
});
test('explicit empty fields restore base independently of favorites and character links', async () => {
  const base = makeBase(); base.tags[0].aliases = ['original']; base.tags[0].note = 'base note';
  const h = createHarness({ base }); await h.ready;
  await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  assert.equal((await run(h.library, { type: 'saveTag', tagId: 'blue_hair', patch: { aliases: [], note: '', displayName: '' } })).ok, true);
  assert.deepEqual(h.library.getTag('blue_hair').aliases, []); assert.equal(h.library.getTag('blue_hair').displayName, '');
  const document = await h.repository.read(); assert.equal(document.customTags.length, 0); assert.deepEqual(document.tagOverrides[0].patch.aliases, []);
  await run(h.library, { type: 'restoreTag', tagId: 'blue_hair' });
  assert.deepEqual(h.library.getTag('blue_hair').aliases, ['original']); assert.equal(h.library.getMemberships().length, 1);
  assert.deepEqual(h.library.getCharacterLinks('alice').generalTagIds, ['blue_hair']);
});
test('placement creates taxonomy and favorites atomically; invalid drafts leave no structure', async () => {
  const h = createHarness(); await h.ready;
  const invalid = await run(h.library, { type: 'saveTag', patch: { content: 'new' }, placement: { kind: 'favorite', page: { create: { name: '新页' } }, group: { id: 'daily' } } });
  assert.equal(invalid.error.code, 'INVALID_PARENT'); assert.equal(h.library.getFavoritePages().length, 1); assert.equal(h.repository.saveCount, 0);
  const added = await run(h.library, { type: 'saveTag', patch: { content: 'new' }, placement: { kind: 'taxonomy', category: { create: { name: '新分类' } }, subcategory: { create: { name: '新子类' } } } });
  assert.equal(added.ok, true); const tag = h.library.getTag(added.data.tagId); assert.equal(tag.source.kind, 'custom');
  assert.equal(h.library.getSubcategories(tag.categoryId)[0].id, tag.subcategoryId);
  const favorite = await run(h.library, { type: 'favoriteTag', tagId: tag.id, placement: { kind: 'favorite', page: { create: { name: '新页' } }, group: { create: { name: '新组' } } } });
  assert.equal(favorite.ok, true); assert.equal(h.library.getFavoritePages().length, 2);
  assert.equal((await run(h.library, { type: 'saveTag', patch: { content: 'new' } })).error.code, 'DUPLICATE_CONTENT');
  assert.equal((await run(h.library, { type: 'saveTag', patch: { content: 'new' }, allowIndependent: true })).ok, true);
});
test('memberships move by exact id, deletion protection and group relocation preserve identity', async () => {
  const h = createHarness(); await h.ready;
  const created = await run(h.library, { type: 'saveTag', patch: { content: 'local' } }); const tagId = created.data.tagId;
  const a = await run(h.library, { type: 'favoriteTag', tagId, placement });
  const g = await run(h.library, { type: 'saveGroup', pageId: 'home', name: 'Other' });
  const other = { ...placement, group: { id: g.data.groupId } };
  await run(h.library, { type: 'favoriteTag', tagId, placement: other });
  assert.equal(h.library.getMemberships(tagId).length, 2);
  assert.equal((await run(h.library, { type: 'deleteTag', tagId })).error.code, 'TAG_IN_USE');
  assert.equal((await run(h.library, { type: 'move', tagId, placement: other })).error.code, 'INVALID_FIELD');
  assert.equal((await run(h.library, { type: 'move', tagId: 'long_hair', placement: { ...other, membershipId: a.data.membershipId } })).error.code, 'INVALID_PARENT');
  assert.equal((await run(h.library, { type: 'deleteGroup', groupId: g.data.groupId, mode: 'relocate' })).ok, true);
  assert.equal(h.library.getMemberships(tagId).length, 2);
  const uncategorizedPage = h.library.getFavoritePages().find(page => page.name === '未分类');
  assert.equal(h.library.getFavoriteGroups(uncategorizedPage.id)[0].name, '未分类');
  await run(h.library, { type: 'unfavorite', membershipIds: h.library.getMemberships(tagId).map(m => m.id) });
  assert.equal((await run(h.library, { type: 'deleteTag', tagId })).ok, true);
  assert.equal((await run(h.library, { type: 'deleteTag', tagId: 'blue_hair' })).error.code, 'BUNDLED_TAG_NOT_DELETABLE');
});
test('historical migration maps survive unfavorite and deletion without resurrecting live records', async () => {
  const h = createHarness(); await h.ready;
  const created = await run(h.library, { type: 'saveTag', patch: { content: 'legacy' } });
  const favorite = await run(h.library, { type: 'favoriteTag', tagId: created.data.tagId, placement });
  const doc = await h.repository.read(); doc.migration = { id: 'm1', sourceFingerprint: 'legacy', completedAt: 0, tagIdMap: { old: created.data.tagId }, favoriteIdMap: { old: favorite.data.membershipId }, characterIdMap: {}, counts: { sourceTags: 1, sourceFavorites: 1, linkedFavorites: 1, independentFavorites: 0, unresolved: 0 } };
  const next = createHarness({ document: doc }); assert.equal((await next.ready).ok, true);
  assert.equal((await run(next.library, { type: 'unfavorite', membershipIds: [favorite.data.membershipId] })).ok, true);
  assert.equal((await run(next.library, { type: 'deleteTag', tagId: created.data.tagId })).ok, true);
  assert.equal(next.library.getTag(created.data.tagId), null); assert.deepEqual((await next.repository.read()).migration, doc.migration);
});
test('reorder validates complete siblings; category and character edits enforce relationships', async () => {
  const h = createHarness(); await h.ready;
  const group = await run(h.library, { type: 'saveGroup', pageId: 'home', name: 'Other' });
  assert.equal((await run(h.library, { type: 'reorder', kind: 'group', parentId: 'home', ids: ['daily'] })).error.code, 'INVALID_FIELD');
  assert.equal((await run(h.library, { type: 'reorder', kind: 'group', parentId: 'home', ids: [group.data.groupId, 'daily'] })).ok, true);
  assert.equal(h.library.getFavoriteGroups('home')[0].id, group.data.groupId);
  assert.equal((await run(h.library, { type: 'saveCategory', id: 'hair', name: '发型' })).ok, true);
  assert.equal(h.library.getCategories()[0].name, '发型');
  assert.equal((await run(h.library, { type: 'saveSubcategory', id: 'color', categoryId: 'hair', name: '色彩' })).ok, true);
  const links = h.library.getCharacterLinks('alice'); links.generalTagIds = ['long_hair'];
  assert.equal((await run(h.library, { type: 'editCharacter', characterId: 'alice', identityPatch: { content: 'Alice in Wonderland', aliases: [] }, links })).ok, true);
  assert.equal(h.library.getTag('alice').content, 'Alice in Wonderland'); assert.deepEqual(h.library.getCharacterLinks('alice').generalTagIds, ['long_hair']);
  assert.equal((await run(h.library, { type: 'saveTag', tagId: 'alice', patch: { kind: 'bundle' } })).error.code, 'TAG_IN_USE');
});
test('missing storage is initialized with production defaults, corrupt storage stays read-only, outputs are copied', async () => {
  const h = createHarness({ document: null }); assert.equal((await h.ready).ok, true); assert.equal(h.repository.saveCount, 1);
  assert.equal(h.library.getFavoritePages().length, 0); assert.match((await h.repository.read()).libraryId, /^library:/);
  const first = h.library.getTag('blue_hair'); first.aliases.push('mutated'); assert.deepEqual(h.library.getTag('blue_hair').aliases, []);
  const bad = emptyUserDocument(); bad.memberships.push({ id: 'bad', tagId: 'missing', groupId: 'daily', order: 0, pinned: false });
  const broken = createHarness({ document: bad }); assert.equal((await broken.ready).error.code, 'UNRESOLVED_REFERENCE');
  assert.equal(broken.library.status().writable, false); assert.equal(broken.repository.saveCount, 0);
});
test('independent duplicates can be edited without reauthorizing their unchanged content; occupied moves are atomic', async () => {
  const h = createHarness(); await h.ready;
  const duplicate = await run(h.library, { type: 'duplicateTag', tagId: 'blue_hair' });
  assert.equal(duplicate.ok, true);
  assert.equal((await run(h.library, { type: 'saveTag', tagId: duplicate.data.tagId, patch: { note: 'independent note' } })).ok, true);
  const other = await run(h.library, { type: 'saveGroup', pageId: 'home', name: 'Other' });
  const first = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement: { ...placement, group: { id: other.data.groupId } } });
  const before = h.library.getMemberships('blue_hair');
  const move = await run(h.library, { type: 'move', tagId: 'blue_hair', placement: { ...placement, group: { id: other.data.groupId }, membershipId: first.data.membershipId } });
  assert.equal(move.error.code, 'DUPLICATE_MEMBERSHIP'); assert.deepEqual(h.library.getMemberships('blue_hair'), before);
});
test('all batch variants, exact move, page relocation and structure edits commit real state', async () => {
  const h = createHarness(); await h.ready;
  const first = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  const second = await run(h.library, { type: 'favoriteTag', tagId: 'long_hair', placement });
  const newPage = await run(h.library, { type: 'savePage', name: 'Page 2', color: '#123456', colorMode: 'custom' });
  const newGroup = await run(h.library, { type: 'saveGroup', pageId: newPage.data.pageId, name: 'Group 2' });
  assert.equal((await run(h.library, { type: 'batch', operations: [
    { type: 'pin', membershipIds: [first.data.membershipId], pinned: true },
    { type: 'colorPages', pageIds: ['home'], colorMode: 'custom', color: '#abcdef' },
    { type: 'move', tagId: 'long_hair', placement: { kind: 'favorite', page: { id: newPage.data.pageId }, group: { id: newGroup.data.groupId }, membershipId: second.data.membershipId } }
  ] })).ok, true);
  assert.equal(h.library.getMemberships('blue_hair')[0].pinned, true); assert.equal(h.library.getFavoritePages()[0].color, '#abcdef');
  assert.equal(h.library.getMemberships('long_hair')[0].id, second.data.membershipId);
  assert.equal((await run(h.library, { type: 'savePage', id: newPage.data.pageId, name: 'Renamed' })).ok, true);
  assert.equal((await run(h.library, { type: 'saveGroup', id: newGroup.data.groupId, pageId: newPage.data.pageId, name: 'Renamed group' })).ok, true);
  assert.equal((await run(h.library, { type: 'reorder', kind: 'page', parentId: null, ids: [newPage.data.pageId, 'home'] })).ok, true);
  assert.equal((await run(h.library, { type: 'deletePage', pageId: newPage.data.pageId, mode: 'relocate' })).ok, true);
  const uncategorizedPage = h.library.getFavoritePages().find(page => page.name === '未分类');
  const uncategorizedGroup = h.library.getFavoriteGroups(uncategorizedPage.id).find(group => group.name === '未分类');
  assert.equal(h.library.getMemberships('long_hair')[0].groupId, uncategorizedGroup.id);
  assert.equal((await run(h.library, { type: 'move', tagId: 'blue_hair', placement: { kind: 'favorite', page: { id: uncategorizedPage.id }, group: { id: uncategorizedGroup.id }, membershipId: first.data.membershipId } })).ok, true);
  assert.equal((await run(h.library, { type: 'reorder', kind: 'membership', parentId: uncategorizedGroup.id, ids: [second.data.membershipId, first.data.membershipId] })).ok, true);
  assert.equal(h.library.listTags({ scope: 'favorites', groupId: uncategorizedGroup.id, includeAdult: true }).items[0].id, 'long_hair');
  assert.equal((await run(h.library, { type: 'move', tagId: 'blue_hair', placement: { kind: 'taxonomy', category: { id: 'hair' }, subcategory: { id: 'shape' } } })).ok, true);
  assert.equal(h.library.getTag('blue_hair').subcategoryId, 'shape');
  const before = await h.repository.read();
  assert.equal((await run(h.library, { type: 'batch', operations: [{ type: 'unfavorite', membershipIds: [first.data.membershipId] }, { type: 'pin', membershipIds: ['missing'], pinned: true }] })).ok, false);
  assert.deepEqual(await h.repository.read(), before);
  assert.equal((await run(h.library, { type: 'deletePage', pageId: 'home', mode: 'unfavorite' })).ok, true);
  assert.equal(h.library.getMemberships().length, 2);
  assert.equal((await run(h.library, { type: 'deletePage', pageId: uncategorizedPage.id, mode: 'unfavorite' })).ok, true);
  assert.equal(h.library.getMemberships().length, 0); assert.ok(h.library.getTag('blue_hair'));
});
test('relocation reuses only the named uncategorized destination and preserves merged pins and display order', async () => {
  const h = createHarness(); await h.ready;
  const untouchedPage = await run(h.library, { type: 'savePage', name: 'Keep this page' });
  await run(h.library, { type: 'saveGroup', pageId: untouchedPage.data.pageId, name: 'Not a relocation destination' });
  const page = await run(h.library, { type: 'savePage', name: '未分类' });
  const untouchedGroup = await run(h.library, { type: 'saveGroup', pageId: page.data.pageId, name: 'Keep this group' });
  const group = await run(h.library, { type: 'saveGroup', pageId: page.data.pageId, name: '未分类' });
  const target = { kind: 'favorite', page: { id: page.data.pageId }, group: { id: group.data.groupId } };
  const alice = await run(h.library, { type: 'favoriteTag', tagId: 'alice', placement: target });
  const blue = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement: target });
  const sourceBlue = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  const long = await run(h.library, { type: 'favoriteTag', tagId: 'long_hair', placement });
  const other = await run(h.library, { type: 'saveGroup', pageId: 'home', name: 'First group' });
  const uniform = await run(h.library, { type: 'favoriteTag', tagId: 'specific:uniform', placement: { ...placement, group: { id: other.data.groupId } } });
  await run(h.library, { type: 'batch', operations: [{ type: 'pin', membershipIds: [sourceBlue.data.membershipId], pinned: true }] });
  await run(h.library, { type: 'reorder', kind: 'group', parentId: 'home', ids: [other.data.groupId, 'daily'] });
  const targetBefore = h.library.getMemberships().filter(row => row.groupId === group.data.groupId);
  assert.equal((await run(h.library, { type: 'deletePage', pageId: 'home', mode: 'relocate' })).ok, true);
  assert.deepEqual(h.library.getFavoritePages().map(row => row.id), [untouchedPage.data.pageId, page.data.pageId]);
  assert.deepEqual(h.library.getFavoriteGroups(page.data.pageId).map(row => row.id), [untouchedGroup.data.groupId, group.data.groupId]);
  const rows = h.library.getMemberships().sort((a, b) => a.order - b.order);
  assert.deepEqual(rows.map(row => row.id), [alice.data.membershipId, blue.data.membershipId, uniform.data.membershipId, long.data.membershipId]);
  assert.deepEqual(rows.slice(0, 2).map(row => row.order), targetBefore.map(row => row.order));
  assert.equal(rows[1].pinned, true); assert.equal(rows.length, 4);
  assert.ok(rows.every(row => row.groupId === group.data.groupId));
});
test('relocation creates the fixed destination atomically and can replace a deleted uncategorized group or page', async () => {
  const h = createHarness(); await h.ready;
  const favorite = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  const before = await h.repository.read(); const events = []; h.library.subscribe(event => events.push(event));
  h.controls.failNextSave();
  assert.equal((await run(h.library, { type: 'deleteGroup', groupId: 'daily', mode: 'relocate' })).error.code, 'STORAGE_WRITE_FAILED');
  assert.deepEqual(await h.repository.read(), before); assert.equal(events.length, 0);
  assert.equal((await run(h.library, { type: 'deleteGroup', groupId: 'daily', mode: 'relocate' })).ok, true);
  let page = h.library.getFavoritePages().find(row => row.name === '未分类');
  let group = h.library.getFavoriteGroups(page.id).find(row => row.name === '未分类');
  assert.equal(h.library.getMemberships('blue_hair')[0].groupId, group.id);
  const oldGroupId = group.id;
  assert.equal((await run(h.library, { type: 'deleteGroup', groupId: oldGroupId, mode: 'relocate' })).ok, true);
  group = h.library.getFavoriteGroups(page.id).find(row => row.name === '未分类');
  assert.notEqual(group.id, oldGroupId); assert.equal(h.library.getMemberships('blue_hair')[0].groupId, group.id);
  const oldPageId = page.id;
  assert.equal((await run(h.library, { type: 'deletePage', pageId: oldPageId, mode: 'relocate' })).ok, true);
  page = h.library.getFavoritePages().find(row => row.name === '未分类');
  assert.notEqual(page.id, oldPageId);
  group = h.library.getFavoriteGroups(page.id).find(row => row.name === '未分类');
  assert.equal(h.library.getMemberships('blue_hair')[0].groupId, group.id);
  assert.equal(h.library.getMemberships('blue_hair')[0].id, favorite.data.membershipId);
  assert.equal(h.library.getMemberships().length, 1); assert.ok(h.library.getTag('blue_hair'));
});
test('favoriteTag rejects membershipId without moving or creating drafts; explicit move and editor save retain their semantics', async () => {
  const h = createHarness(); await h.ready;
  const first = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  const before = await h.repository.read(), saves = h.repository.saveCount;
  const rejected = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement: { kind: 'favorite', page: { create: { name: 'Draft page' } }, group: { create: { name: 'Draft group' } }, membershipId: first.data.membershipId } });
  assert.equal(rejected.error?.code, 'INVALID_FIELD');
  assert.deepEqual(await h.repository.read(), before); assert.equal(h.repository.saveCount, saves);
  const other = await run(h.library, { type: 'saveGroup', pageId: 'home', name: 'Other' });
  const destination = { ...placement, group: { id: other.data.groupId } };
  const second = await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement: destination });
  assert.equal(second.ok, true); assert.notEqual(second.data.membershipId, first.data.membershipId);
  assert.equal(h.library.getMemberships('blue_hair').find(row => row.id === first.data.membershipId).groupId, 'daily');
  assert.equal((await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement: destination })).data.changed, false);
  const third = await run(h.library, { type: 'saveGroup', pageId: 'home', name: 'Third' });
  assert.equal((await run(h.library, { type: 'move', tagId: 'blue_hair', placement: { ...placement, group: { id: third.data.groupId }, membershipId: first.data.membershipId } })).ok, true);
  assert.equal((await run(h.library, { type: 'saveTag', tagId: 'blue_hair', patch: { note: 'editor save' }, placement: { ...placement, membershipId: second.data.membershipId } })).ok, true);
  assert.equal(h.library.getMemberships('blue_hair').find(row => row.id === second.data.membershipId).groupId, 'daily');
  assert.equal(h.library.getMemberships('blue_hair').find(row => row.id === first.data.membershipId).groupId, third.data.groupId);
  assert.equal(h.library.getTag('blue_hair').note, 'editor save');
});
test('discovery filters do not affect explicit browsing and validation errors report actual limits', async () => {
  const h = createHarness(); await h.ready;
  assert.ok(h.library.getTag('specific:uniform'));
  assert.equal(h.library.search('school uniform', { scope: 'all', includeAdult: true }).total, 0);
  await run(h.library, { type: 'favoriteTag', tagId: 'blue_hair', placement });
  await run(h.library, { type: 'saveTag', tagId: 'blue_hair', patch: { searchable: false } });
  assert.equal(h.library.search('blue hair', { scope: 'favorites', includeAdult: true }).total, 0);
  assert.equal(h.library.listTags({ scope: 'favorites', includeAdult: true }).total, 1);
  const tooLarge = await run(h.library, { type: 'saveTag', tagId: 'blue_hair', patch: { content: 'x'.repeat(32769) } });
  assert.equal(tooLarge.error.code, 'INVALID_FIELD'); assert.match(tooLarge.error.message, /32768/);
});
